included:
  - Sources
  - Tests

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - sorted_imports

line_length:
  warning: 120
  error: 160

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

function_body_length:
  warning: 50
  error: 80

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y

reporter: "xcode"
